### ISSUE TITLE
Pretrained checkpoints?

### ISSUE THREAD

**Issue by anusfoil** [rsy1026/sketching_piano_expression#1]
Hi! I am also working in generating expressive performances and I would like to compare with your model's generation in evaluation! I wonder if there is any pretrained checkpoints for inference so that I can render a custom testing set for comparison without training it from scratch?

**Comment by rsy1026** [comment]
Hi! Thank you for your interest! 
Yes, I can share a pretrained checkpoint. Would you give me an email address that I can send to?

**Comment by anusfoil** [comment]
Sure! huan.zhang@qmul.ac.uk, and thanks a lot!
